CREATE TABLE IF NOT EXISTS users (
  userId VARCHAR(36) PRIMARY KEY,
  username VARCHAR() NOT NULL UNIQUE,
  password VARCHAR() NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT now()
);


